namespace CDV_Viewer;

public enum TypesErreurVerif
{
	VoieSansNoeuds = 101,
	VoieSansDebut = 102,
	VoieSansFin = 103,
	VoiePkDebutFaux = 104,
	VoiePkFinFaux = 105,
	NoeudPlus4Branches = 201,
	NoeudPlus2BranchesAmont = 202,
	NoeudPlus2BranchesAval = 203,
	NoeudBranchesPlus3VoiesDifferentes = 204,
	NoeudPlus2BranchesSurMemeVoie = 205,
	JointTypeInconnu = 301,
	JointSurAucuneVoie = 302,
	JointAvantDebutVoie = 303,
	JointApresFinVoie = 304,
	JointRelieAucunCircuit = 305,
	JointReliePlus2Circuits = 306,
	JointLiaisonIncorrecte = 307,
	JointLongueurNonCorrecte = 308,
	JointDoitEtreJI = 309,
	CircuitTypeInconnu = 401,
	CircuitMoins2Joints = 402,
	CircuitPlusDe6Joints = 403,
	CircuitJointsPrincipauxDifferent2 = 404,
	CircuitLiaisonIncorrecte = 405,
	CircuitParcoursInterneIncorrect = 406,
	CircuitFrequenceIncorrecte = 407,
	CircuitCompensationIncorrecte = 408,
	CircuitDonneesLongueurOuCompensationIncorrecte = 409,
	ModeleIdJointIncorrect = 501,
	ModeleDemiPasDifferentDeDemiPasDemiJoint = 502,
	ModeleNbCondosDifferentNbCondosCircuit = 503,
	ModeleDonneesLongueurOuCompensationCircuitIncorrecte = 504,
	ModeleLongueurDifferentLongueurCircuit = 505,
	ModeleSansCircuit = 506
}
